### ISSUE TITLE
Create a blog post about LLaMA

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/anamnesis.ai#5]
the blog post should be create at opensciencelabs.org
https://github.com/OpenScienceLabs/opensciencelabs.github.io

**Comment by Satarupa22-SD** [comment]
@xmnlab Please close this issue. Thanks !

**Comment by xmnlab** [comment]
thanks! @Satarupa22-SD !
ps: I just add you here as maintainer, so you should be able to close issues as well :)
